### ISSUE TITLE
Drag and drop doesn't work in firefox.

### ISSUE THREAD

**Issue by Vishnu2jd** [vojkovic/searxng#13]
When text is highlighted, drag and drop into new tab doesn't work in Firefox. Other searxng instances has no issues with this. But it does work in chromium.

**Comment by vojkovic** [comment]
Hi Vishnu2jd, I don't quite understand the issue... could you pleas elaborate a bit. Thanks.

**Comment by Vishnu2jd** [comment]
When you select text and drag into new tab, it should perform search for the text. But instead it opens to home page.

https://user-images.githubusercontent.com/87307728/174718065-875f66eb-1eda-4e0e-b1e8-987ccbc8a709.mov

For another searxng instance.
https://user-images.githubusercontent.com/87307728/174718036-fe09874a-64b6-48f4-bb80-ff8326227943.mov

**Comment by vojkovic** [comment]
I apologize for the delay,

Unfortunately, I wont do anything about this. The issue you are experiencing is due to my instance choosing to default to POST rather than GET requests. 

I do not use GET requests as that requires the query to be in the URL and is bad for user privacy as searches are displayed in history.

Other SearXNG instances that use POST by default have the same problem.

The Chromium Project does not support search engines using POST, so GET is used instead.
